# Generated by Django 2.2.3 on 2021-06-25 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('target_departament', models.CharField(choices=[('sal', 'Sales'), ('mar', 'Marketing'), ('HR', 'Human Resources'), ('non', 'None')], default='non', max_length=3)),
                ('target_location', models.CharField(choices=[('WAW', 'Warszawa'), ('KRK', 'Kraków'), ('PZN', 'Poznań'), ('non', 'None')], default='non', max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollSubmition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitions', to='polls.Poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('enabletext', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('mch', 'Multiple Choice'), ('chc', 'Choice'), ('txt', 'Text'), ('pck', 'Pick from list'), ('dat', 'Date')], default='chc', max_length=3)),
                ('poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.Poll')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PollSubmitionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('manyanswer', models.ManyToManyField(blank=True, related_name='submitions', to='polls.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitions', to='polls.Question')),
                ('submition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitions', to='polls.PollSubmition')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.Question'),
        ),
    ]
