# Generated by Django 3.1.1 on 2020-10-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='textanswer',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
