# Generated by Django 3.1.1 on 2020-10-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201010_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='body',
            new_name='title',
        ),
    ]
