# Generated by Django 3.1.1 on 2020-10-10 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_auto_20201010_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollSubmition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ManyToManyField(to='polls.Poll')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollSubmitionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.poll'),
        ),
        migrations.DeleteModel(
            name='PollFinishFlag',
        ),
        migrations.AddField(
            model_name='pollsubmitionquestion',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitions', to='polls.answer'),
        ),
        migrations.AddField(
            model_name='pollsubmitionquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitions', to='polls.question'),
        ),
        migrations.AddField(
            model_name='pollsubmitionquestion',
            name='submition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitions', to='polls.pollsubmition'),
        ),
    ]
