# Generated by Django 3.1.1 on 2020-10-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201010_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='published_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
