# Generated by Django 3.1.1 on 2020-10-20 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_poll_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='textanswer',
        ),
        migrations.AddField(
            model_name='pollsubmition',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
