# Generated by Django 2.2.3 on 2020-11-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20201020_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollsubmitionquestion',
            name='text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
