# Generated by Django 2.2.3 on 2020-11-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_pollsubmitionquestion_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
