# Generated by Django 2.2.3 on 2020-11-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
    ]
