# Generated by Django 2.2.3 on 2020-11-14 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20201114_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollsubmitionquestion',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitions', to='polls.Answer'),
        ),
    ]
