# Generated by Django 2.2.3 on 2020-11-17 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0011_auto_20201114_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollsubmition',
            name='poll',
        ),
        migrations.AddField(
            model_name='pollsubmition',
            name='poll',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
        migrations.RemoveField(
            model_name='pollsubmition',
            name='user',
        ),
        migrations.AddField(
            model_name='pollsubmition',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
