# Generated by Django 2.2.3 on 2020-11-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20201117_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mch', 'Multiple Choice'), ('chc', 'Choice'), ('txt', 'Text'), ('pck', 'Pick from list'), ('dat', 'Date')], default='chc', max_length=3),
        ),
    ]
