# Generated by Django 2.2.3 on 2020-11-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20201122_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='date',
        ),
        migrations.AddField(
            model_name='pollsubmitionquestion',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
