# Generated by Django 2.2.3 on 2021-04-22 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20201122_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollsubmitionquestion',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pollsubmition',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitions', to='polls.Poll'),
        ),
    ]
