# Generated by Django 2.2.3 on 2021-04-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20210422_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollsubmitionquestion',
            name='answer',
            field=models.TextField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
