# Generated by Django 3.1.1 on 2021-05-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20210422_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='target_departament',
            field=models.CharField(choices=[('sal', 'Sales'), ('mar', 'Marketing'), ('HR', 'Human Resources'), ('ALL', 'All')], default='ALL', max_length=3),
        ),
        migrations.AddField(
            model_name='poll',
            name='target_location',
            field=models.CharField(choices=[('WAW', 'Warszawa'), ('KRK', 'Kraków'), ('PZN', 'Poznań'), ('ALL', 'All')], default='ALL', max_length=3),
        ),
    ]
