# Generated by Django 3.1.1 on 2021-05-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_pollsubmitionquestion_manyanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollsubmitionquestion',
            name='manyanswer',
        ),
        migrations.AddField(
            model_name='pollsubmitionquestion',
            name='manyanswer',
            field=models.ManyToManyField(blank=True, null=True, related_name='submitions', to='polls.Answer'),
        ),
    ]
