# Generated by Django 3.2.4 on 2021-06-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20210526_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='target_departament',
            field=models.CharField(choices=[('sal', 'Sales'), ('mar', 'Marketing'), ('HR', 'Human Resources'), ('non', 'None')], default='ALL', max_length=3),
        ),
        migrations.AlterField(
            model_name='poll',
            name='target_location',
            field=models.CharField(choices=[('WAW', 'Warszawa'), ('KRK', 'Kraków'), ('PZN', 'Poznań'), ('non', 'None')], default='ALL', max_length=3),
        ),
    ]
