# Generated by Django 3.1.1 on 2021-06-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20210608_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='target_departament',
            field=models.CharField(choices=[('sal', 'Sales'), ('mar', 'Marketing'), ('HR', 'Human Resources'), ('non', 'None')], default='non', max_length=3),
        ),
        migrations.AlterField(
            model_name='poll',
            name='target_location',
            field=models.CharField(choices=[('WAW', 'Warszawa'), ('KRK', 'Kraków'), ('PZN', 'Poznań'), ('non', 'None')], default='non', max_length=3),
        ),
        migrations.AlterField(
            model_name='pollsubmitionquestion',
            name='manyanswer',
            field=models.ManyToManyField(blank=True, related_name='submitions', to='polls.Answer'),
        ),
    ]
