# Generated by Django 3.1.1 on 2021-07-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgecategory',
            options={'verbose_name_plural': 'Knowledge Categories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='slug', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NewsReadFlag',
        ),
    ]
