# Generated by Django 2.2.3 on 2021-04-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_docfile_docquestion_documentf_userquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentf',
            name='target_departament',
            field=models.CharField(choices=[('sal', 'Sales'), ('mar', 'Marketing'), ('HR', 'Human Resources'), ('ALL', 'All')], default='ALL', max_length=3),
        ),
        migrations.AddField(
            model_name='documentf',
            name='target_location',
            field=models.CharField(choices=[('WAW', 'Warszawa'), ('KRK', 'Kraków'), ('PZN', 'Poznań'), ('ALL', 'All')], default='ALL', max_length=3),
        ),
    ]
