# Generated by Django 3.1.1 on 2021-07-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210706_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docquestion',
            name='body',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
