# Generated by Django 2.2.3 on 2021-04-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210415_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='docfile',
            name='target_departament',
            field=models.CharField(choices=[('sal', 'Sales'), ('mar', 'Marketing'), ('HR', 'Human Resources'), ('ALL', 'All')], default='ALL', max_length=3),
        ),
        migrations.AddField(
            model_name='docfile',
            name='target_location',
            field=models.CharField(choices=[('WAW', 'Warszawa'), ('KRK', 'Kraków'), ('PZN', 'Poznań'), ('ALL', 'All')], default='ALL', max_length=3),
        ),
        migrations.AddField(
            model_name='docquestion',
            name='answer',
            field=models.TextField(default=None, max_length=5000),
        ),
        migrations.AddField(
            model_name='docquestion',
            name='target_departament',
            field=models.CharField(choices=[('sal', 'Sales'), ('mar', 'Marketing'), ('HR', 'Human Resources'), ('ALL', 'All')], default='ALL', max_length=3),
        ),
        migrations.AddField(
            model_name='docquestion',
            name='target_location',
            field=models.CharField(choices=[('WAW', 'Warszawa'), ('KRK', 'Kraków'), ('PZN', 'Poznań'), ('ALL', 'All')], default='ALL', max_length=3),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='body',
            field=models.TextField(default=None, max_length=5000),
            preserve_default=False,
        ),
    ]
