# Generated by Django 2.2.3 on 2021-04-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210415_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfile',
            name='isnews',
            field=models.BooleanField(default=True),
        ),
    ]
