# Generated by Django 2.2.3 on 2021-07-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210706_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
