# Generated by Django 2.2.3 on 2021-04-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210419_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docquestion',
            name='answer',
            field=models.TextField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
