# Generated by Django 3.1.1 on 2021-07-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_docfile_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docquestion',
            options={'ordering': ['-id']},
        ),
    ]
