# Generated by Django 3.1.1 on 2021-07-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20210712_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date', '-date_created', 'id'], 'verbose_name_plural': 'news'},
        ),
    ]
