# Generated by Django 2.2.3 on 2021-04-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_documentcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentCategory',
            new_name='KnowledgeCategory',
        ),
    ]
