# Generated by Django 2.2.3 on 2021-04-21 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20210419_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='docquestion',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documentf',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='docs', to='news.KnowledgeCategory'),
        ),
    ]
