# Generated by Django 3.1.1 on 2021-06-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20210608_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docfile',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='documentf',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='docfile',
            name='target_departament',
            field=models.CharField(choices=[('sal', 'Sales'), ('mar', 'Marketing'), ('HR', 'Human Resources'), ('non', 'None')], default='non', max_length=3),
        ),
        migrations.AlterField(
            model_name='docfile',
            name='target_location',
            field=models.CharField(choices=[('WAW', 'Warszawa'), ('KRK', 'Kraków'), ('PZN', 'Poznań'), ('non', 'None')], default='non', max_length=3),
        ),
        migrations.AlterField(
            model_name='docquestion',
            name='target_departament',
            field=models.CharField(choices=[('sal', 'Sales'), ('mar', 'Marketing'), ('HR', 'Human Resources'), ('non', 'None')], default='non', max_length=3),
        ),
        migrations.AlterField(
            model_name='docquestion',
            name='target_location',
            field=models.CharField(choices=[('WAW', 'Warszawa'), ('KRK', 'Kraków'), ('PZN', 'Poznań'), ('non', 'None')], default='non', max_length=3),
        ),
        migrations.AlterField(
            model_name='documentf',
            name='target_departament',
            field=models.CharField(choices=[('sal', 'Sales'), ('mar', 'Marketing'), ('HR', 'Human Resources'), ('non', 'None')], default='non', max_length=3),
        ),
        migrations.AlterField(
            model_name='documentf',
            name='target_location',
            field=models.CharField(choices=[('WAW', 'Warszawa'), ('KRK', 'Kraków'), ('PZN', 'Poznań'), ('non', 'None')], default='non', max_length=3),
        ),
        migrations.AlterField(
            model_name='news',
            name='target_departament',
            field=models.CharField(choices=[('sal', 'Sales'), ('mar', 'Marketing'), ('HR', 'Human Resources'), ('non', 'None')], default='non', max_length=3),
        ),
        migrations.AlterField(
            model_name='news',
            name='target_location',
            field=models.CharField(choices=[('WAW', 'Warszawa'), ('KRK', 'Kraków'), ('PZN', 'Poznań'), ('non', 'None')], default='non', max_length=3),
        ),
        migrations.AlterField(
            model_name='newsfile',
            name='target_departament',
            field=models.CharField(choices=[('sal', 'Sales'), ('mar', 'Marketing'), ('HR', 'Human Resources'), ('non', 'None')], default='non', max_length=3),
        ),
        migrations.AlterField(
            model_name='newsfile',
            name='target_location',
            field=models.CharField(choices=[('WAW', 'Warszawa'), ('KRK', 'Kraków'), ('PZN', 'Poznań'), ('non', 'None')], default='non', max_length=3),
        ),
    ]
