# Generated by Django 3.1.1 on 2021-06-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfile',
            name='isnews',
        ),
        migrations.RemoveField(
            model_name='newsfile',
            name='target_departament',
        ),
        migrations.RemoveField(
            model_name='newsfile',
            name='target_location',
        ),
    ]
