# Generated by Django 3.1.1 on 2021-06-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20210619_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfile',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
