# Generated by Django 2.2.3 on 2021-06-25 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='profile_pics/default-profile.png', upload_to='profile_pics')),
                ('name', models.CharField(max_length=30)),
                ('telephone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('date_of_employement', models.DateField(default=django.utils.timezone.now)),
                ('employee_id', models.PositiveIntegerField()),
                ('position', models.CharField(default='trainee', max_length=40)),
                ('departament', models.CharField(choices=[('sal', 'Sales'), ('mar', 'Marketing'), ('HR', 'Human Resources'), ('non', 'None')], default='non', max_length=3)),
                ('location', models.CharField(choices=[('WAW', 'Warszawa'), ('KRK', 'Kraków'), ('PZN', 'Poznań'), ('non', 'None')], default='non', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
    ]
