# Generated by Django 3.1.1 on 2021-06-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210513_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='vacation_status',
        ),
        migrations.DeleteModel(
            name='Vacation',
        ),
    ]
