# Generated by Django 2.2.3 on 2021-04-08 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devent',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devent',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
