# Generated by Django 3.1.1 on 2021-07-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0002_auto_20210630_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='devent',
            name='slug',
            field=models.SlugField(max_length=20, null=True),
        ),
    ]
