# Generated by Django 2.2.3 on 2021-04-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0003_devent_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devent',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devent',
            name='start',
            field=models.TimeField(default=0),
        ),
    ]
