# Generated by Django 2.2.3 on 2021-04-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0004_auto_20210416_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='devent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
