# Generated by Django 3.1.1 on 2021-06-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendary', '0006_auto_20210612_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devent',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Events', to='calendary.day'),
        ),
        migrations.AlterField(
            model_name='devent',
            name='end',
            field=models.TimeField(default='23:59', verbose_name='Ending time'),
        ),
        migrations.AlterField(
            model_name='devent',
            name='start',
            field=models.TimeField(default='00:00', verbose_name='Start time'),
        ),
    ]
