# Generated by Django 2.2.3 on 2021-03-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcategory',
            name='icon',
            field=models.TextField(blank=True),
        ),
    ]
