# Generated by Django 2.2.3 on 2021-03-24 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_boardcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_answer',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
