# Generated by Django 3.1.1 on 2021-06-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_auto_20210628_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardcategory',
            name='icon',
        ),
    ]
