# Generated by Django 3.1.1 on 2021-07-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0004_auto_20210701_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardcategory',
            options={'verbose_name_plural': 'board categories'},
        ),
    ]
