# Generated by Django 3.1.1 on 2021-07-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0005_auto_20210705_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-last_activity']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='last_comment',
            new_name='last_activity',
        ),
    ]
