# Generated by Django 3.1.1 on 2021-06-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0005_auto_20210419_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date_created']},
        ),
    ]
